---
- hosts: all
  remote_user: root
  tasks:

    - name: "set keyboard layout"
      copy:
        src: "files/etc/default/keyboard"
        dest: "/etc/default/keyboard"
        backup: yes

    - name: "Install needed software"
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - htop
        - inkscape
        - ipython
        - rsync

    - name: "Include enable i2c service"
      include: "playbooks/enable_i2c.yml"

    - name: "Include VNC installation"
      include: "playbooks/install_vnc.yml"

    - name: "Include Eggbot installation"
      include: "playbooks/install_eggbot_extension.yml"

    - name: "Include Murbletrail installation"
      include: "playbooks/install_murbletrail.yml"

    - name: "Set passwords"
      user:
        name: "{{ item }}"
        password: "$6$ov0p2HC4$GE0adXQKMc7Pazx1aPmVH6J4s8bFopGdgKUc2aanDxXHuVDahxBvZlhecvEXXfOpe0FDTyykuFmgn5EKX/eOW1"
        update_password: always
      with_items:
        - root
        - pi

    - name: "Clone RaspberryJam repository"
      git:
        repo: 'https://github.com/magictimelapse/RaspberryJamSchweiz.git'
        dest: /home/pi/RaspberryJamSchweiz
        update: yes
      become: yes
      become_user: pi

    - name: "Remove Games"
      apt:
        name: "{{ item }}"
        state: absent
      with_items:
        - minecraft-pi
        - python3-pygame
